import { copyFile, mkdir, stat } from 'node:fs/promises';
import { dirname, isAbsolute, join, normalize, sep } from 'node:path';

import { git } from './exec.js';

/**
 * Giving a new node's folder what git deliberately left behind.
 *
 * `git worktree add` checks out tracked files only, so everything gitignored
 * stays where it was: no .env, no node_modules, no .venv. The agent lands
 * somewhere the app cannot start and the tests cannot run -- which would make
 * the success criteria from 2.1 report "I wrote the code but could not check
 * anything" almost every time. The two features are one feature.
 *
 * Two mechanisms, because there are two kinds of missing thing. Small files
 * that cannot be regenerated (.env) are copied. Everything that CAN be
 * regenerated (dependencies) is regenerated by the setup command, because
 * copying it is either enormous or actively broken.
 */

export interface SeedFileOutcome {
  path: string;
  copied: boolean;
  /** Why it was not copied. Shown to the user; never silently swallowed. */
  reason?: string;
}

/**
 * Names that are never copied, whatever the setting says.
 *
 * `node_modules` is hundreds of megabytes per node, and a tree of ten nodes
 * would be gigabytes of duplicated packages.
 *
 * A Python virtualenv is worse than large: it is WRONG when moved. The
 * activate scripts and the console entry points bake in the absolute path of
 * the directory they were created in, so a copied .venv runs the wrong
 * interpreter or fails with a path that does not exist -- confusingly, and
 * only at the moment the agent tries to run the tests. That is what the setup
 * command is for.
 */
const NEVER_COPY = new Set(['node_modules', '.venv', 'venv', '.tox', '.git', 'target', 'vendor']);

/**
 * Copies the configured files from the project's own folder into a new worktree.
 *
 * Copies, never symlinks: a symlink means an agent editing .env edits the
 * user's real one, and the entire premise is that a node cannot affect
 * anything outside itself.
 */
export async function seedFiles(opts: {
  /** The project's own folder -- master's checkout. */
  sourceDir: string;
  /** The new node's worktree. */
  targetDir: string;
  files: readonly string[];
}): Promise<SeedFileOutcome[]> {
  const out: SeedFileOutcome[] = [];

  for (const raw of opts.files) {
    const relative = raw.trim();
    if (relative === '') continue;

    const rejection = rejectPath(relative);
    if (rejection !== null) {
      out.push({ path: relative, copied: false, reason: rejection });
      continue;
    }

    const from = join(opts.sourceDir, relative);
    if (!(await isFile(from))) {
      out.push({ path: relative, copied: false, reason: 'not found in the project folder' });
      continue;
    }

    /**
     * THE IMPORTANT CHECK. A file that is tracked by git must not be copied.
     *
     * Bonsai commits with `git add -A`. Copying a TRACKED .env into a node
     * would stage it and commit the user's secrets -- in an adopted project,
     * onto a branch inside their own repository. Refused, with the reason.
     *
     * And refused rather than fixed: adding it to .gitignore is not Bonsai's
     * call. That file is tracked, it exists in every worktree, and in an
     * adopted project it belongs to the user. Editing it is a request to make
     * of the agent, not something a settings field should do behind their back.
     */
    if (await isTracked(opts.sourceDir, relative)) {
      out.push({
        path: relative,
        copied: false,
        reason:
          'it is tracked by git, so copying it would commit its contents to this node’s ' +
          'branch. Add it to .gitignore first (that is a change to your repository, so Bonsai ' +
          'will not make it for you).',
      });
      continue;
    }

    try {
      const to = join(opts.targetDir, relative);
      await mkdir(dirname(to), { recursive: true });
      await copyFile(from, to);
      out.push({ path: relative, copied: true });
    } catch (err) {
      out.push({
        path: relative,
        copied: false,
        reason: err instanceof Error ? err.message : String(err),
      });
    }
  }

  return out;
}

/**
 * Whether this path may be copied at all, ignoring what is on disk.
 *
 * Exported so Settings can refuse a bad entry as it is typed, rather than
 * having it fail silently at every node creation from then on.
 */
export function rejectPath(relative: string): string | null {
  if (isAbsolute(relative)) return 'must be a path inside the project, not an absolute path';

  const normalised = normalize(relative);
  if (normalised.startsWith('..') || normalised.split(/[\\/]/).includes('..')) {
    return 'must stay inside the project folder';
  }

  for (const segment of normalised.split(sep)) {
    if (NEVER_COPY.has(segment)) {
      return segment === 'node_modules'
        ? 'dependencies are far too large to copy per node — use the setup command instead'
        : `${segment} bakes in absolute paths and breaks when copied — use the setup command instead`;
    }
  }
  return null;
}

async function isFile(path: string): Promise<boolean> {
  try {
    return (await stat(path)).isFile();
  } catch {
    return false;
  }
}

/** `git ls-files` rather than `check-ignore`: tracked is the thing that matters. */
async function isTracked(repoDir: string, relative: string): Promise<boolean> {
  try {
    const out = await git(['ls-files', '--error-unmatch', '--', relative], repoDir);
    return out.trim() !== '';
  } catch {
    // Not tracked, or not a repo. Either way it is safe to copy.
    return false;
  }
}
