import { copyFile, lstat, mkdir, stat } from 'node:fs/promises';
import { dirname, isAbsolute, join, normalize, resolve, sep } from 'node:path';

import { git } from './exec.js';

/**
 * Giving a new node's folder what git deliberately left behind.
 *
 * `git worktree add` checks out tracked files only, so everything gitignored
 * stays where it was: no .env, no node_modules, no .venv. The agent lands
 * somewhere the app cannot start and the tests cannot run -- which would make
 * the success criteria from 2.1 report "I wrote the code but could not check
 * anything" almost every time. The two features are one feature.
 *
 * Two mechanisms, because there are two kinds of missing thing. Small files
 * that cannot be regenerated (.env) are copied. Everything that CAN be
 * regenerated (dependencies) is regenerated by the setup command, because
 * copying it is either enormous or actively broken.
 */

export interface SeedFileOutcome {
  path: string;
  copied: boolean;
  /** Why it was not copied. Shown to the user; never silently swallowed. */
  reason?: string;
}

/**
 * Names that are never copied, whatever the setting says.
 *
 * `node_modules` is hundreds of megabytes per node, and a tree of ten nodes
 * would be gigabytes of duplicated packages.
 *
 * A Python virtualenv is worse than large: it is WRONG when moved. The
 * activate scripts and the console entry points bake in the absolute path of
 * the directory they were created in, so a copied .venv runs the wrong
 * interpreter or fails with a path that does not exist -- confusingly, and
 * only at the moment the agent tries to run the tests. That is what the setup
 * command is for.
 */
const NEVER_COPY = new Set(['node_modules', '.venv', 'venv', '.tox', '.git', 'target', 'vendor']);

/**
 * Copies the configured files from the project's own folder into a new worktree.
 *
 * Copies, never symlinks: a symlink means an agent editing .env edits the
 * user's real one, and the entire premise is that a node cannot affect
 * anything outside itself.
 */
export async function seedFiles(opts: {
  /** The project's own folder -- master's checkout. */
  sourceDir: string;
  /** The new node's worktree. */
  targetDir: string;
  files: readonly string[];
}): Promise<SeedFileOutcome[]> {
  const out: SeedFileOutcome[] = [];

  for (const raw of opts.files) {
    const relative = raw.trim();
    if (relative === '') continue;

    const rejection = rejectPath(relative);
    if (rejection !== null) {
      out.push({ path: relative, copied: false, reason: rejection });
      continue;
    }

    const from = join(opts.sourceDir, relative);
    if (!(await isFile(from))) {
      out.push({ path: relative, copied: false, reason: 'not found in the project folder' });
      continue;
    }

    try {
      await rejectSymlinks(opts.sourceDir, relative);
      await rejectSymlinks(opts.targetDir, relative);
      for (const dir of [opts.sourceDir, opts.targetDir]) {
        if ((await git(['ls-files', '--', relative], dir)).trim() !== '') {
          throw new Error(
            'This file is tracked by git. Ignoring it alone does not untrack it; review its tracking in your repository before copying it.',
          );
        }
      }
      // Check the destination: source-only ignore rules need not exist in a worktree.
      try {
        await git(['check-ignore', '-q', '--', relative], opts.targetDir);
      } catch {
        throw new Error(
          'The destination must gitignore this file before it can be copied. Could not verify that it is ignored.',
        );
      }
      const to = join(opts.targetDir, relative);
      await mkdir(dirname(to), { recursive: true });
      await rejectSymlinks(opts.targetDir, relative);
      await copyFile(from, to);
      out.push({ path: relative, copied: true });
    } catch (err) {
      out.push({
        path: relative,
        copied: false,
        reason: err instanceof Error ? err.message : String(err),
      });
    }
  }

  return out;
}

/**
 * Whether this path may be copied at all, ignoring what is on disk.
 *
 * Exported so Settings can refuse a bad entry as it is typed, rather than
 * having it fail silently at every node creation from then on.
 */
export function rejectPath(relative: string): string | null {
  if (isAbsolute(relative)) return 'must be a path inside the project, not an absolute path';

  const normalised = normalize(relative);
  if (normalised.startsWith('..') || normalised.split(/[\\/]/).includes('..')) {
    return 'must stay inside the project folder';
  }

  for (const segment of normalised.split(sep)) {
    if (NEVER_COPY.has(segment)) {
      return segment === 'node_modules'
        ? 'dependencies are far too large to copy per node — use the setup command instead'
        : `${segment} bakes in absolute paths and breaks when copied — use the setup command instead`;
    }
  }
  return null;
}

async function isFile(path: string): Promise<boolean> {
  try {
    return (await stat(path)).isFile();
  } catch {
    return false;
  }
}

/** Refuse symlink components, including the root and an existing destination file. */
async function rejectSymlinks(root: string, path: string): Promise<void> {
  const boundary = resolve(root);
  const full = resolve(boundary, path);
  let cursor = full;
  while (true) {
    try {
      if ((await lstat(cursor)).isSymbolicLink())
        throw new Error('Copy paths must not contain symlinks.');
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
    }
    if (cursor === boundary) break;
    const parent = dirname(cursor);
    if (parent === cursor) break;
    cursor = parent;
  }
}
